server:
  port: 8454
logging:
  file: /java/C2S_LOGS/context-handler/context-handler.log
info:
  component: Context Handler API
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
spring:
  datasource:
    # configure url, username and password per environment
    url: jdbc:mysql://localhost:3306/pcm?autoReconnect=true
    username: root
    password: admin
c2s:
  context-handler:
    pid.type: ISO
    polrep:
      policySet:
        combiningAlgs:
          first-applicable: urn:oasis:names:tc:xacml:1.0:policy-combining-algorithm:first-applicable
          ordered-deny-overrides: urn:oasis:names:tc:xacml:1.1:policy-combining-algorithm:ordered-deny-overrides
          ordered-permit-overrides: urn:oasis:names:tc:xacml:1.1:policy-combining-algorithm:ordered-permit-overrides
          deny-overrides: urn:oasis:names:tc:xacml:1.0:policy-combining-algorithm:deny-overrides
          only-one-applicable: urn:oasis:names:tc:xacml:1.0:policy-combining-algorithm:only-one-applicable
          permit-overrides: urn:oasis:names:tc:xacml:1.0:policy-combining-algorithm:permit-overrides
    pdpRequest:
      resource:
        typeCode: 34133-9
        status: urn:oasis:names:tc:ebxml-regrep:StatusType:Approved
      action:
        actionId: pepaccess
    audit-client:
      enabled: false
      host: localhost
      port: 9630
---
# enables ssl in this service when activated
spring.profiles: ssl
server:
  # configure keystore and keystore password for ssl per environment
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
---
# enables ssl and adds /contextHandler context path when activated
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl
server.context-path: /contextHandler
---
# updates configuration for docker environment
spring:
  profiles: docker
  datasource:
      url: jdbc:mysql://${C2S_DB_HOST:pcm-db.c2s.com}:${C2S_DB_PORT:3306}/pcm?autoReconnect=true
c2s:
  context-handler:
    audit-service:
      host: logback-audit-server.c2s.com